[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://jp.translink.com.au/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 